spring.application.name=approval-service
server.port=8084
#database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/b2bprocurement_platform
spring.datasource.username=root
spring.datasource.password=vinod267
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#eureka configuration

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#actuator configurations
management.endpoints.web.exposure.include=*

#redis configurations
spring.cache.type=redis
spring.cache.cache-names=
spring.data.redis.host=localhost
spring.data.redis.port=6379
